### ISSUE TITLE
Suggest to add a Homepage link on pypi

### ISSUE THREAD

**Issue by paradise321** [toxicphreAK/python-docx-ng#28]
Hey toxicphreAK,
Thanks for the great work done on this project!

Just a small suggestion: better to add a Homepage link on your pypi home(https://pypi.org/project/python-docx-ng/) as others do, that way people can find this repo on github and can follow much easier.

Thanks again!

**Comment by toxicphreAK** [comment]
Hi @paradise321,

thank you for the idea, I changed it, let's see if that drops more people to the repo. 
Actually the side links is missing, but I will try my best in the next releases to have a smooth linking.

**Comment by paradise321** [comment]
You are welcome!
And I saw there are some other projects/repos doing similar things to python-docx-ng:

python-docx-oss：https://github.com/lsaint/python-docx-oss/blob/master/HISTORY.md
python-docx-arg："A fork of python-docx with fixes for IWF report generation tools", https://pypi.org/project/python-docx-arg/, seems discontinued.
python-docx-valutico："This is basically the same as python-docx, but with added support for charts. "
python-docx-lists："python-docx fork with support of some addition list settings like justification"
python-docx-replace：https://github.com/ivanbicalho/python-docx-replace

We may pick those commits to python-docx-ng on a regular basis, say every month or so.

In this way, the project can attract more attention from people who access PyPi and Github by releasing new versions on a regular basis.
